### ISSUE TITLE
Loading session is _slow_

### ISSUE THREAD

**Issue by smunaut** [lambdaconcept/usb2sniffer-qt#2]
Attached is a capture of a USB stick enumeration. At the beginning, there is a _ton_ of IN/NAK until the device is actually ready and loading this file takes forever. It also progressively slows down making things worse.

[test.zip](https://github.com/lambdaconcept/usb2sniffer-qt/files/3063600/test.zip)

**Comment by jeanthom** [comment]
I ran lcsniff under Apple's Instruments.app. It seems that `USBModel::addPacket()` takes a lot of time to execute during the parsing (especially `USBModel::updateNodes()`), and then the widget drawing in `QWidgetPrivate::drawWidget` also takes ages.

**Comment by smunaut** [comment]
Yes, for such a large number of items, letting Qt manage things isn't a good approach. You basically need to handle the scrolling manually and create / destroy the Qt List items "on the fly" just for the visible window of items.

**Comment by jeanthom** [comment]
It seems we can make things much faster by calling `USBModel::updateNodes()` once we've loaded all the packets (it takes 5 secs) instead of calling it on every `USBMode::addPacket()`. However I still have widget drawing issues.

**Comment by jeanthom** [comment]
https://github.com/lambdaconcept/usb2sniffer-qt/commit/70a7e47f5476bc4cae1f13d50c4fade44143d33d should improve performance in QTreeView, can you give it a try ?

Otherwise I will send other patches soon that should improve performance when parsing files.

**Comment by jeanthom** [comment]
https://github.com/lambdaconcept/usb2sniffer-qt/pull/6 did improve loading times (on a 10 Mb file we get down to 6 seconds on macOS).

**Comment by smunaut** [comment]
Loading the example file at the top of this issue still takes ~ 150 seconds here. Definitely better than before (I don't know how long it took but I killed it after 5-10 min).
But once loaded, browsing in it is fluid enough.

**Comment by smunaut** [comment]
Oh no sorry, forget what I said ... I thought that it had been merged (I saw some perf commits by you in master ...).

I now have tried with #6  and it is _MUCH_ faster ... indeed takes about 5-6 second to load the example file I provided.

@jeanthom Thanks !
