### ISSUE TITLE
Windows 1.0 build always shows empty device list

### ISSUE THREAD

**Issue by r1cebank** [lambdaconcept/usb2sniffer-qt#31]
Hi, I downloaded the lcsniff-1.0-win-64 from the github releases but the windows prebuilt seems to not working for me. I have tried using on Linux and everything works for my device.

I am using Windows 10 20H2

**Comment by jeanthom** [comment]
Hi, what kind of issues are you experiencing with the Windows build?

**Comment by r1cebank** [comment]
Hi, when I use the Windows build, after plugging in the device, the application seems to not able to detect the device, after checking the code and a pending PR https://github.com/lambdaconcept/usb2sniffer-qt/pull/18, it appears that this option is not used for Windows.

Even without selecting the option, I am still not able to have the application to detect the device. Please let me know if I am doing anything wrong. I am still able to get the application working under Linux so it is not a crucial issue for me.

![image](https://user-images.githubusercontent.com/261671/103101907-93c9fd80-45ce-11eb-9054-c058918a01b5.png)

**Comment by povauboin** [comment]
The setting is not used for windows and is now hidden.
https://github.com/lambdaconcept/usb2sniffer-qt/releases/tag/1.1
